name: starter_template
version: 1.0.0

environment:
  sdk: ^2.17.0

dependencies:
  path: ^1.9.0
  dart_appwrite: ^20.1.1
  googleapis_auth: ^2.0.0
  http: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
